feat(headless): Add IP Tab controller
coveo/ui-kit pull request #2200
Opened 2022-07-08 11:59 UTC by aelfaleh

- https://coveord.atlassian.net/browse/SVCC-2209

2022-07-11 12:42 UTC, nathanlb commented
Looks like there are more changes here than just the tab controller. I think it would be helpful to reviewers if you could add some more info in the PR description.

2022-07-13 13:36 UTC, nathanlb approved these changes

2022-07-13 13:36 UTC, nathanlb commented on packages/headless/src/controllers/insight/query-summary/headless-insight-query-summary.ts
>   * Creates a `InsightQuerySummary` controller instance.
Like with the others we should change the name in the jsdoc as well to be consistent.

2022-07-13 19:56 UTC, lbergeron approved these changes
It looks quite good!

2022-07-13 19:56 UTC, lbergeron commented on packages/headless/src/controllers/core/tab/headless-core-tab.ts
> +   * The options for the `CoreTab` controller.
```suggestion
   * The options for the `Tab` controller.
```

2022-07-13 19:56 UTC, lbergeron commented on packages/headless/src/controllers/core/tab/headless-core-tab.ts
> +   * The state of the `CoreTab` controller.
```suggestion
   * The state of the `Tab` controller.
```

2022-07-13 19:56 UTC, lbergeron commented on packages/headless/src/controllers/insight/tab/headless-insight-tab.test.ts
> +    });
I suggest we keep only this test. The others are all duplicates of the core test suite.

2022-07-13 19:59 UTC, nathanlb commented on packages/headless/src/controllers/insight/tab/headless-insight-tab.ts
> + * Creates an insight `Tab` controller instance.
If you want to add it in your other renaming PR then I'm on board :)

2022-07-18 17:37 UTC, btaillon approved these changes

2022-07-21 18:41 UTC, erocheleau requested changes
Just small changes then good to go!

2022-07-21 18:41 UTC, erocheleau commented on packages/headless/src/controllers/core/tab/headless-core-tab.test.ts
> +  it('it adds the correct reducers to engine', () => {
```suggestion
  it('adds the correct reducers to engine', () => {
```

2022-07-21 18:41 UTC, erocheleau commented on packages/headless/src/controllers/core/tab/headless-core-tab.test.ts
> +    it('does not throw if initialState is undefined', () => {
should we test that it initializes correctly and not just that it doesn't throw?

2022-07-21 18:41 UTC, erocheleau commented on packages/headless/src/controllers/core/tab/headless-core-tab.test.ts
> +      expect(engine.actions).toContainEqual(updateActiveTab(id));
should you expect that the state isActive is also true?

2022-07-21 18:41 UTC, erocheleau commented on packages/headless/src/controllers/core/tab/headless-core-tab.test.ts
> +    it('dispatches #updateActiveTab', () => {
might be a nice test also to validate that when another tab was already active, after select() then this tab isActive and the other tab is no longer active?

2022-07-25 18:31 UTC, erocheleau approved these changes

2022-07-25 20:18 UTC, merged