feat(atomic): remove atomic-insight-breadbox from docs, warn when implementing...
coveo/ui-kit pull request #2295
Opened 2022-08-05 10:22 UTC by liviarett

breadbox with non-search

I actually didn't find any mention of the breadbox in the Figma file, so removed it at least for now!

https://coveord.atlassian.net/browse/KIT-1907

2022-08-05 12:44 UTC, ThibodeauJF requested changes
This will break implementations using `atomic-external`

2022-08-05 12:45 UTC, ThibodeauJF commented on packages/atomic/src/components/search/atomic-breadbox/atomic-breadbox.tsx
> +    if (!closest(this.host, 'atomic-search-interface')) {
Maybe the bindings could contain what type of interface you're connected to (search/insight)

2022-08-05 13:19 UTC, olamothe reviewed
I understand the JS doc removal, but why explicitly add code for this specific component that verifies that the parent is a search interface, and not for all the other search components ?

The "convention" we went with is that implementers should be using components that match for `insight` (ie: will contain the `insight` prefix in the component tag name).

The changes in atomic-breadbox seems superfluous ?

2022-08-05 14:19 UTC, liviarett commented
@olamothe you're right, I think that because it kind of works with the wrong interface already without changing anything, I wanted to make sure it was clear that it wasn't meant to be used like that. but I agree that it should be handled somewhere else and in a more generic way!

2022-08-05 20:04 UTC, btaillon approved these changes

2022-08-08 13:55 UTC, ThibodeauJF approved these changes

2022-08-08 16:38 UTC, merged