feat(quantic): add focus control for facetValue
coveo/ui-kit pull request #2379
Opened 2022-08-26 16:01 UTC by MSLI-Coveo

[2292](https://coveord.atlassian.net/browse/SVCC-2292) 
Add focus control for facetValue

2022-08-31 18:15 UTC, erocheleau requested changes
Simplify the code a little bit if it's possible?

2022-08-31 20:22 UTC, MSLI-Coveo commented on packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
> +    this.facetContentChanged = true;
renderedCallback still needed after testing.

2022-08-31 20:26 UTC, MSLI-Coveo commented on packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
> +    this.facetContentChanged = true;
setFocus needed to be fired inside renderedCallback.

2022-08-31 20:29 UTC, MSLI-Coveo commented on packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.js
> +    this.htlmElement.focus();
new setFocus added

2022-08-31 20:29 UTC, MSLI-Coveo commented on packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.js
> +
method removed

2022-08-31 21:32 UTC, lvu285 commented
Can I see the demo?

2022-09-06 21:27 UTC, erocheleau approved these changes

2022-09-06 21:45 UTC, merged