(headless): when a tab is selected, the pagination resets to 1
coveo/ui-kit pull request #2757
Opened 2023-03-03 19:22 UTC by drosenfeld-coveo

[SFINT-4860](https://coveord.atlassian.net/browse/SFINT-4860)

Small change so when we change tabs, it will reset to the first page

Steps to test:
1. Open a atomic(or quantic) insight panel with multiple tabs and pages
2. go to page 2 on the first tab
3. switch to another tab
4. Page should be changed to 1 after swaping tabs

2023-03-03 21:04 UTC, ThibodeauJF approved these changes
Looks good, I don't think the package-lock.json should be part of the PR tho!

you can run something like `git checkout master package-lock.json`

2023-03-06 13:43 UTC, btaillon requested changes
Requested change because of my comment.

2023-03-07 14:34 UTC, btaillon approved these changes

2023-03-09 20:41 UTC, jelmedini approved these changes
looks good !!

2023-03-09 20:41 UTC, jelmedini commented on packages/headless/src/features/pagination/pagination-slice.test.ts
> +  it('#updateActiveTab sets sets the #firstResult to 0', () => {
not sure to understand this sentence, maybe a more explicit description ?

2023-03-09 22:34 UTC, louis-bompart commented on packages/headless/src/integration-tests/field-suggestions.test.ts
> +      const rawValue = 'PDF';
Done in #2771

2023-03-09 22:34 UTC, louis-bompart approved these changes

2023-03-14 14:40 UTC, mmitiche approved these changes

2023-03-14 18:46 UTC, merged