feat(atomic): add styling to the ipx scroll bar
coveo/ui-kit pull request #2830
Opened 2023-04-13 20:35 UTC by jbvouma

[SVCINT-2279](https://coveord.atlassian.net/browse/SVCINT-2279)

Added some custom styling to the IPX scroll bar.

Here is an example:

- Chrome
![chrome](https://user-images.githubusercontent.com/67848363/231876591-fb9ee658-f821-46ab-816e-aeecde202a1c.JPG)

- Firefox
![Firefox](https://user-images.githubusercontent.com/67848363/231876758-747bdbcd-fcf7-4358-b279-7f722e4005a8.JPG)

- Edge
![edge](https://user-images.githubusercontent.com/67848363/231876790-dbc3afa1-8383-4d46-ab70-0e74c4f41cca.JPG)

2023-04-14 12:52 UTC, btaillon approved these changes

2023-04-14 19:18 UTC, pathiery requested changes
UX said that they'd prefer background but really we need to wait for UX to finish their color related investigations before applying these changes

2023-04-20 13:50 UTC, mikegron approved these changes

2023-04-25 17:04 UTC, pathiery approved these changes

2023-04-25 17:56 UTC, dguerinCoveo approved these changes
Looks good imo. Definitely an upgrade

2023-05-02 10:36 UTC, merged