fix(headless,headless-react): make ssr terminology more consistent
coveo/ui-kit pull request #3159
Opened 2023-09-08 22:10 UTC by btaillon

https://coveord.atlassian.net/browse/KIT-2680

Here's a chart of the server-side-rendering flow:
```mermaid
sequenceDiagram
  participant Headless as @coveo/headless
  participant Static as Static definition
  participant SSR as Server-side
  participant CSR as Client-side
  alt Create definition
    Static->>+Headless: const definition = defineSearchEngine({ ... });
    Headless->>-Static: engine definition
  end
  CSR->>+SSR: request page
  alt Execute the first search
    SSR->>+Static: const stateA = definition.getStateA();
    Static->>SSR: First search response
    Static->>-SSR: State of every controller
  end
  alt render page
    SSR->>SSR: const html = generateHTMLFromState(stateA.controllers);
  end
  SSR->>CSR: send html
  SSR->>-CSR: send stateA
  CSR->>CSR: display HTML
  alt Resume search / obtain new controllers
    CSR->>+Static: const stateB = definition.getStateB(stateA.searchResponse);
    Static->>CSR: Search engine
    Static->>-CSR: Controllers
  end
  CSR->>CSR: subscribe to controllers
```

For StateA and StateB, we've been using inconsistent terminology.

In this PR, my goal is to align all the terms to be consistent. Here are the two main options we've been discussing:
* Option 1 (option I picked): for stateA, use "initial state". For stateB, use "hydrated state"
  * A file shared between both server and client calls `defineSearchEngine`, which returns an `EngineDefinition<...>`
  * The server calls `fetchInitialState`
    * Returns an `InitialState<...>`
  * The client calls `hydrateInitialState`
    * Takes an `InitialState<...>` as a parameter.
    * Returns an `HydratedState<...>`
* Option 2: for stateA, use "ssrState". For stateB, use "csrResult"
  * A file shared between both server and client calls `defineSearchEngine`, which returns an `EngineDefinition<...>`
  * The server calls `fetchSSRState`
    * Returns a `SSRState<...>`
  * The client calls `hydrateSSRState`(?)
    * Takes a `SSRState<...>` as a parameter.
    * Returns a `CSRState<...>`

I picked option 1, since it feels more natural to me after all.

2023-09-11 13:14 UTC, dmbrooke approved these changes
I like this language much more, it's very natural 🙂

2023-09-11 19:16 UTC, olamothe approved these changes

2023-09-11 20:13 UTC, louis-bompart approved these changes
LGTM, better 💯

2023-09-12 23:53 UTC, mrrajamanickam-coveo requested changes
Reads better overall! 
Just a couple of places that got missed.

2023-09-12 23:53 UTC, mrrajamanickam-coveo commented on packages/headless-react/src/types.ts
>    CSRProvider: FunctionComponent<
CSRProvider -> HydratedStateProvider ?

2023-09-12 23:53 UTC, mrrajamanickam-coveo commented on packages/headless-react/src/search-engine.test.tsx
>      test('should render with SSRProvider', async () => {
test desc needs to be updated

2023-09-12 23:53 UTC, mrrajamanickam-coveo commented on packages/headless/src/app/ssr-engine/types/common.ts
> +export interface HydratedState<
Nice! Reads better.

2023-09-12 23:53 UTC, mrrajamanickam-coveo commented on packages/samples/headless-ssr/src/app/react/components/search-page.tsx
> +  const [hydratedState, setCSRResult] = useState<
setCSRResult -> setHydratedState

2023-09-13 14:02 UTC, btaillon commented
Woops, missed those because I was doing a search and replace for SSR/CSR State to Static/Hydrated state.

Tried again, but this time used regular expressions like `CSR([A-Z][a-z]*)` -> `Hydrated$1` and `Static(?!State|Filter|CDN|Facet|Response|Resource)([A-Z][a-z]*)` -> `StaticState$1` to catch more. Of course, I didn't blindly approve every replacement.

2023-09-13 20:13 UTC, mrrajamanickam-coveo approved these changes

2023-09-13 20:39 UTC, merged