ci: split headless-ssr in dev and prod
coveo/ui-kit pull request #3259
Opened 2023-10-06 20:08 UTC by alexprudhomme

https://coveord.atlassian.net/browse/KIT-2783

2023-10-06 20:10 UTC, mrrajamanickam-coveo requested changes

2023-10-06 20:10 UTC, mrrajamanickam-coveo commented on .github/workflows/prbot.yml
> +    name: 'Run e2e tests on Headless SSR sample in dev'
```suggestion
    name: 'Run e2e tests on Headless SSR sample in prod'
```

2023-10-06 20:10 UTC, mrrajamanickam-coveo commented on .github/workflows/prbot.yml
> +    name: 'Run e2e tests on Headless SSR sample in dev'
similar name mismatches above as well

2023-10-06 20:11 UTC, alexprudhomme commented on .github/workflows/prbot.yml
> +    name: 'Run e2e tests on Headless SSR sample in dev'
oops !

2023-10-06 21:37 UTC, mrrajamanickam-coveo commented on .github/workflows/masterbot.yml
> +    name: 'Run e2e tests on Headless SSR sample in prod'
misspell here as well and below

2023-10-11 20:47 UTC, mrrajamanickam-coveo approved these changes

2023-10-12 19:21 UTC, dmbrooke approved these changes

2023-10-13 12:27 UTC, merged