fix(error) added margin at the buttom of the error component
coveo/ui-kit pull request #3486
Opened 2023-12-14 20:58 UTC by drosenfeld-coveo

[SVCC-3252](https://coveord.atlassian.net/browse/SVCC-3252)

added padding the bottom of the error component
before: 
![image](https://github.com/coveo/ui-kit/assets/96303212/74e61afb-7591-4623-9565-3480a44fa10e)

after:
<img width="684" alt="Screenshot 2023-12-14 at 3 50 00 PM" src="https://github.com/coveo/ui-kit/assets/96303212/ce1c6c18-9302-4631-9491-a038836e0bdd">

blue line added to show margin

2023-12-15 15:52 UTC, olamothe requested changes
It would be better to add that margin at a "higher" (more specific) level in the food chain than that low level component (that is used in different context). Because otherwise you make it so that component has some magic margin that might not make sense in all context.

Alternative are: 

* In the .html page, in the layout section itself that holds the atomic-insight-query-error
* In the `atomic-insight-query-error.tsx` file itself.

2023-12-15 17:41 UTC, nathanlb commented
> It would be better to add that margin at a "higher" (more specific) level in the food chain than that low level component (that is used in different context). Because otherwise you make it so that component has some magic margin that might not make sense in all context.
> 
> Alternative are:
> 
> * In the .html page, in the layout section itself that holds the atomic-insight-query-error
> * In the `atomic-insight-query-error.tsx` file itself.

I'm the one that suggested the spacing could be added to the base component. Is there a scenario where we would not want proper spacing with whatever is around this error component?

2023-12-21 20:32 UTC, nathanlb approved these changes

2023-12-29 18:11 UTC, louis-bompart approved these changes

2024-01-03 19:37 UTC, merged