fix(atomic): ensure redirection on instant result click
coveo/ui-kit pull request #3585
Opened 2024-02-07 20:06 UTC by y-lakhdar

The redirection fails to occur based on the user's click location within the instant result.

This problem arises when the mouse click event target is 'atomic-result,' preventing the 'atomic-search-box-instant-results' from extracting the document URI.

KIT-2993

2024-02-07 21:47 UTC, louis-bompart requested changes
I think the getLink should be agnostic of where the user click on a result.
I'll open a counter-proposal 🔜

2024-02-07 21:48 UTC, fbeaudoincoveo approved these changes

2024-02-07 21:54 UTC, louis-bompart commented
https://github.com/coveo/ui-kit/commit/6a8641a0864618598fc221d1c11423affefeb0a9

`getLink` is called when we declare the Node/Element of the `atomic-result` we want to 'bind' ourselves to.
So let's just grab a ref and use it instead of depending on what exact element caught the click initially.

2024-02-12 15:48 UTC, louis-bompart approved these changes

2024-02-12 15:48 UTC, merged