feat(Commerce Atomic): `add atomic-commerce-numeric-facet`
coveo/ui-kit pull request #3954
Opened 2024-05-16 15:43 UTC by y-lakhdar

Add new atomic-commerce-numeric-facet component

KIT-3179

2024-05-17 15:33 UTC, fpbrault approved these changes

2024-05-17 15:33 UTC, fpbrault commented on packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
> +
```suggestion
/**
 * The `atomic-commerce-numeric-facet` component is responsible for rendering a commerce facet that allows the user to filter products using numeric ranges.
 *
 * @internal
 */
```

2024-05-17 15:33 UTC, fpbrault commented on packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
> +
```suggestion
 /**
   * The field whose values you want to display in the facet.
   */
```

2024-05-17 15:46 UTC, olamothe requested changes

2024-05-17 15:46 UTC, olamothe commented on packages/atomic/src/components/commerce/facets/facet-number-input/atomic-commerce-facet-number-input.tsx
> +import {NumericFacet} from '@coveo/headless/commerce';
For this one, we should definitely refactor and share a lot more code with `atomic-facet-number-input`.

We just need to make sure there is no reliance on any `@coveo/headless` type (just primitive) and there's no reason we cannot use the same input for both type of facets.

2024-05-21 17:53 UTC, olamothe approved these changes

2024-05-22 13:28 UTC, fbeaudoincoveo commented on packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
> +   * The field whose values you want to display in the facet.
I think this should be

"The numeric facet controller instance"

2024-05-22 13:38 UTC, fbeaudoincoveo approved these changes

2024-05-22 13:38 UTC, fbeaudoincoveo commented on packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
> +      this.summary = buildListingSummary(this.bindings.engine);
should the summary controller be passed down as a prop from the parent search interface rather than initializing it here?

2024-05-22 13:38 UTC, fbeaudoincoveo commented on packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
> +  private get numberOfSelectedValues() {
we could add this information in the controller state

2024-05-22 13:38 UTC, fbeaudoincoveo commented on packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
> +  private get valuesToRender() {
It could also be worthwhile to add this information in the numeric facet controller state

2024-05-23 13:08 UTC, merged