feat(headless): expose deselectAll method on facet manager
coveo/ui-kit pull request #4067
Opened 2024-06-10 14:41 UTC by fpbrault

This PR adds a `deselectAll` method on the facet manager controller as already present on the breadcrumb manager controller.

https://coveord.atlassian.net/browse/KIT-3288

2024-06-10 15:41 UTC, fbeaudoincoveo requested changes
Wrong controllers 😅 

It's the commerce facet generator that should have the deselectAll method, not the facet managers.

2024-06-10 19:43 UTC, fbeaudoincoveo approved these changes

2024-06-10 19:43 UTC, fbeaudoincoveo commented on packages/headless/src/controllers/facets/automatic-facet-generator/headless-automatic-facet-generator.ts
> +   * Deselects all automatic facet values.
```suggestion
   * Deselects all values in all facets.
```

2024-06-11 12:24 UTC, olamothe approved these changes

2024-06-12 13:18 UTC, merged