feat(atomic): add tab support for atomic-smart-snippet
coveo/ui-kit pull request #4221
Opened 2024-07-24 15:35 UTC by fpbrault

This PR allows `atomic-smart-snippet` to be visible/hidden based on the currently active tab in the tab manager.

2024-07-24 18:47 UTC, fbeaudoincoveo approved these changes

2024-07-26 10:01 UTC, louis-bompart requested changes
- Some quirky logic to fix
- Test locator are not good enough IMO.

Question: Did you check manually the overall accessibility of the tabs?
While there might be a11y compliant, it doesn't mean it's "good enough".
A good read on tab for accessibility: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/

2024-07-26 13:40 UTC, fpbrault commented on packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/page-object.ts
The locators for tabsArea and tabDropdown aren't but the tests for them are checking that they are visible/not visible.

Aren't `tabButtons` and `tabDropdownOptions` fine though? They use a base locator to get the correct type of element, but can then filter on the text content

2024-07-26 13:47 UTC, louis-bompart commented on packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/page-object.ts
Essentially, my comment is motivated by https://playwright.dev/docs/best-practices#test-user-visible-behavior.

Having only selector built by page.locator and no locators built using label, text, role, or other means is a red flag in term of accessibility.

Yes, accessible-based locators are more prone to breaking than CSS-based selectors, but this is feature, not a bug: it's very easy to break accessiblity, and having accessibility-based selectors help solving that.

A recent example of 'gotcha' those accessibility-based selectors caught: https://github.com/coveo/ui-kit/pull/4219#discussion_r1692051607

2024-07-26 13:51 UTC, fpbrault commented on packages/atomic/src/utils/tab-utils.ts
> +export function shouldDisplayOnCurrentTab(
includes() does a SameValueZero check, so it will only return true if the strings are an exact match.

2024-07-29 14:06 UTC, fpbrault commented on packages/atomic/src/utils/tab-utils.ts
> +export function shouldDisplayOnCurrentTab(
Yep and `shouldDisplayOnCurrentTab` only takes string arrays now! I had made the change in `updateFacetVisibilityForActiveTab` but forgot `shouldDisplayOnCurrentTab`!

2024-08-08 17:02 UTC, alexprudhomme approved these changes

2024-08-08 20:59 UTC, merged