chore(headless)!: remove headless fetch & crypto polyfills
coveo/ui-kit pull request #4358
Opened 2024-08-29 14:09 UTC by alexprudhomme

https://coveord.atlassian.net/browse/KIT-3023

This PR is part of the making sure there are no 'require's in the headless ESM output.
#### Before

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/7869429b-69ef-4c11-801f-35ed35208bab">

#### After

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/a31f7733-676d-4eca-a201-dc746772222a">

-  [x] Remove undici from renovate.json

There is still this one that we will have to change or make it only available to the commonJs output. https://github.com/coveo/ui-kit/blob/KIT-3023/packages/headless/ponyfills/abortable-fetch-shim.js

2024-08-29 15:35 UTC, louis-bompart commented
@coveo/salesforce-integration  can you help @alexprudhomme  check/ensure that the IIFE bundle for Quantic are still kosher?

2024-08-29 15:52 UTC, alexprudhomme commented
> @coveo/salesforce-integration can you help @alexprudhomme check/ensure that the IIFE bundle for Quantic are still kosher?

I think it should be fine since I did not touch the quanticUmd build phase in headless/dist/quantic

https://github.com/coveo/ui-kit/blob/KIT-3023/packages/headless/esbuild.mjs#L140-L163

2024-08-30 12:19 UTC, olamothe approved these changes

2024-08-30 14:02 UTC, mmitiche commented
> @coveo/salesforce-integration can you help @alexprudhomme check/ensure that the IIFE bundle for Quantic are still kosher?

I will do a quick sanity check/test from this PR to double check the Headless quantic bundle is still working property inside Salesforce.

2024-08-30 15:32 UTC, erocheleau commented
Yea we need to check with multiple configuration after this has changed:

1. With LWS enabled
2. With LockerService instead of LWS
3. With Locker disabled in a community.
4. In a LWR site.

@mmitiche if you have the time, please put ✅ if you have tested some of these, I can try to test the others :)

2024-08-30 17:59 UTC, erocheleau requested changes
Just making sure this isn't merged before it has been properly tested

2024-08-30 17:59 UTC, erocheleau commented on packages/headless/esbuild.mjs
> -          'fetch-ponyfill-browser.js'
In think until we figure out why we needed to polyfill fetch for a browser, we shouldn't be confident to remove it?

2024-08-30 19:38 UTC, mmitiche commented
Quantic working properly with:

- With LWS enabled ✅
- With LockerService instead of LWS ✅
- With Locker disabled in a community ✅ 
- In a LWR site ✅

2024-09-03 12:40 UTC, fbeaudoincoveo approved these changes

2024-09-05 15:10 UTC, erocheleau approved these changes
Looks good, thanks for making the tests!

I also confirmed that none of the Crypto stuff was needed due to any Locker/LWS limitation or distortion!

GG

2024-09-05 17:34 UTC, merged