test(atomic): add tests for atomic-product-description
coveo/ui-kit pull request #4547
Opened 2024-10-16 16:03 UTC by fpbrault

This PR adds playwright tests for atomic-product-description

https://coveord.atlassian.net/browse/KIT-3266

2024-10-17 20:19 UTC, fbeaudoincoveo requested changes

2024-10-17 20:25 UTC, fbeaudoincoveo commented on packages/atomic/src/components/commerce/product-template-components/atomic-product-description/e2e/atomic-product-description.e2e.ts
> +  test.describe('when description is truncated', async () => {
Same here, we could test that passing an invalid value throws a validation error.

2024-10-17 20:25 UTC, fbeaudoincoveo commented on packages/atomic/src/components/commerce/product-template-components/atomic-product-excerpt/e2e/atomic-product-excerpt.e2e.ts
> +import {test, expect} from './fixture';
The comments I made above about testing prop validation errors apply here as well.

2024-10-18 22:02 UTC, fpbrault commented
closing as I'm merging this with #4541

2024-10-18 22:02 UTC, closed without merging