fix(quantic): headless quantic bundle updated to support sending RGA feedback when LWS is disabled
coveo/ui-kit pull request #4781
Opened 2024-12-10 12:49 UTC by mmitiche

## [SFINT-5858](https://coveord.atlassian.net/browse/SFINT-5858)

2024-12-10 15:29 UTC, alexprudhomme approved these changes
Thanks for the explanation !

2024-12-11 02:09 UTC, louis-bompart requested changes
I think the root cause for the Request object issue is not what's reported, thus the fix is not adequate.
See https://www.npmjs.com/package/abortcontroller-polyfill

> If you also need a Request class with support for aborting you can do:
> ```js
> const { AbortController, abortableFetch } = require('abortcontroller-polyfill/dist/cjs-ponyfill');
> const _nodeFetch = require('node-fetch');
> const { fetch, Request } = abortableFetch({fetch: _nodeFetch, Request: _nodeFetch.Request});
> 
> const controller = new AbortController();
> const signal = controller.signal;
> controller.abort();
> fetch(Request("http://api.github.com", {signal}))
>   .then(r => r.json())
>   .then(j => console.log(j))
>   .catch(err => {
>       if (err.name === 'AbortError') {
>           console.log('aborted');
>       }
>   })
> ```


So, something like that:
```ts
import {abortableFetch as abortableFetchFactory} from 'abortcontroller-polyfill/dist/cjs-ponyfill';

export {
  AbortController,
  AbortSignal,
} from 'abortcontroller-polyfill/dist/cjs-ponyfill';

const {fetch: abortableFetch, request: abortableRequest} = abortableFetchFactory({
  fetch,
  Request
});

export {abortableFetch as fetch, abortableRequest as Request};
```

in the abortable-fetch-shim should be more adequate I think

Granted, they speaks of NodeJS here, but LWS is similar to Node pre 16, where fetch was not a built-in API: It can be anything ish, and Fetch, Header, Request all need to come from the same "place"

2024-12-12 10:48 UTC, mmitiche commented
> I think the root cause for the Request object issue is not what's reported, thus the fix is not adequate. See https://www.npmjs.com/package/abortcontroller-polyfill
> 
> > If you also need a Request class with support for aborting you can do:
> > ```js
> > const { AbortController, abortableFetch } = require('abortcontroller-polyfill/dist/cjs-ponyfill');
> > const _nodeFetch = require('node-fetch');
> > const { fetch, Request } = abortableFetch({fetch: _nodeFetch, Request: _nodeFetch.Request});
> > 
> > const controller = new AbortController();
> > const signal = controller.signal;
> > controller.abort();
> > fetch(Request("http://api.github.com", {signal}))
> >   .then(r => r.json())
> >   .then(j => console.log(j))
> >   .catch(err => {
> >       if (err.name === 'AbortError') {
> >           console.log('aborted');
> >       }
> >   })
> > ```
> 
> So, something like that:
> 
> ```ts
> import {abortableFetch as abortableFetchFactory} from 'abortcontroller-polyfill/dist/cjs-ponyfill';
> 
> export {
>   AbortController,
>   AbortSignal,
> } from 'abortcontroller-polyfill/dist/cjs-ponyfill';
> 
> const {fetch: abortableFetch, request: abortableRequest} = abortableFetchFactory({
>   fetch,
>   Request
> });
> 
> export {abortableFetch as fetch, abortableRequest as Request};
> ```
> 
> in the abortable-fetch-shim should be more adequate I think
> 
> Granted, they speaks of NodeJS here, but LWS is similar to Node pre 16, where fetch was not a built-in API: It can be anything ish, and Fetch, Header, Request all need to come from the same "place"



Tried it but unfortunately the abortableRequest generated does not seem to do it, I'm trying to run the following script: https://github.com/mmitiche/example-abortable-fetch/blob/main/index.js after injecting the following shim: https://github.com/mmitiche/example-abortable-fetch/blob/main/shim.js


Investigating if we have other workarounds 🤨

2024-12-12 21:08 UTC, SimonMilord approved these changes

2024-12-16 21:07 UTC, erocheleau reviewed
I'm curious too about @louis-bompart explanation, before we merge this.

2025-01-22 14:50 UTC, merged